project:
  type: website
  pre-render:
    - R/cleanup.R
    - R/fetch.R
    - R/setup.R
  post-render:
    - R/finish.R

title-block-banner: "images/iena_banner.jpg"
title-block-banner-color: "#3e3e3e"

website:
  title: "CD Avenches"
  navbar:
    background: "#3e3e3e"
    left:
      - href: index.qmd
        text: Accueil
      - href: programme.qmd
      - href: actuel/Carré_A.qmd
      - href: actuel/Carré_B.qmd
  page-footer:
    left:
      - text: "EquiEvents"
    right: 
      - text: "info@equievents.ch"
        href: "mailto:info@equievents.ch"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    lang: fr
    execute:
      echo: false
      warning: false

editor: visual

